
package socketpractica;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class VisorTelnet extends javax.swing.JFrame {

    /**
     * Creates new form VisorTelnet
     */
    
    
    EchoClient olt = new EchoClient();
    public String vlanInternet;
    public String vlanIptv;
    
    public VisorTelnet() {
        this.vlanIptv = "";
        this.vlanInternet="";
        initComponents();    
        this.txtPort.requestFocus();
        areatxt.setEditable(false);
        radioiptvcero.setSelected(true);
        this.setResizable(false);  
        txtPort.setNextFocusableComponent(txtPos);
        
        
        /*// SE PROCESA EL ARCHIVO PLANO DE CONFIGURACION Y SE AGREGA AL COMBOBOX
         String strLine = null;
         try{
            FileInputStream fstream = new FileInputStream("K:\\Solo Cursos\\TodoJavaUniversidad\\socketPractica\\src\\socketpractica\\Config.txt");
            DataInputStream in = new DataInputStream(fstream);
            BufferedReader br = new BufferedReader(new InputStreamReader(in));
     
            Scanner entrada = new Scanner(fstream);
            ComboBoxOlts.addItem("");
             while (entrada.hasNext()) {
                strLine = entrada.nextLine();
                ComboBoxOlts.addItem(strLine);
                System.out.println(strLine);
              }
      
            in.close();
          }catch (Exception e){
            System.err.println("Error: " + e.getMessage());
  }*/
        
        
 
    }
    

    public static void lanzarTiposDeMensaje(String mensaje) {
        //Propiedad del sistema para salto linea:
        String newline = System.getProperty("line.separator");
        //Mensaje (Se usara en todos los dialogos):
        Object msj = mensaje;
        JOptionPane.showMessageDialog(null, msj, //Mensaje 
        "Mensaje lanzado por aplicación", //Título
        JOptionPane.ERROR_MESSAGE);//Tipo de mensaje   
    }
    
    public class MyIcon implements Icon{
 
    @Override
    public void paintIcon(Component c, Graphics g, int x, int y) {
        Image image = new ImageIcon(getClass().getResource("/imagenes/pregunta.jpg")).getImage();
        g.drawImage(image, x, y, c);
    }
 
    @Override
    public int getIconWidth() {
        return 50;
    }
 
    @Override
    public int getIconHeight() {
        return 50;
    }

}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoIPTV = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areatxt = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        ComboBoxOlts = new javax.swing.JComboBox<>();
        btnEnviar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        txtPos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSerial = new javax.swing.JTextField();
        txtNomyApe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radioiptvcero = new javax.swing.JRadioButton();
        radioiptvunoOdos = new javax.swing.JRadioButton();
        radioiptv3 = new javax.swing.JRadioButton();
        radioiptvcuatro = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemInterfaceOLT = new javax.swing.JMenuItem();
        itemInterfaceOnu = new javax.swing.JMenuItem();
        itemOnuRunning = new javax.swing.JMenuItem();
        itemPotencia = new javax.swing.JMenuItem();
        itemOnuUnconfig = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemBuscarMac = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        UpdatePassYPassword = new javax.swing.JMenu();
        DeleteONU = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mitmSearchOnu = new javax.swing.JMenuItem();
        mitmRebootOnu = new javax.swing.JMenuItem();
        mitmRestoreDOnu = new javax.swing.JMenuItem();
        mitmDistancia = new javax.swing.JMenuItem();
        mitmStatePon = new javax.swing.JMenuItem();
        mitmInfoPon = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ONU CONFIG");
        setBackground(new java.awt.Color(0, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 153, 153));
        setIconImage(getIconImage());
        setLocation(new java.awt.Point(200, 100));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(181, 200, 172));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        areatxt.setBackground(new java.awt.Color(0, 0, 0));
        areatxt.setColumns(20);
        areatxt.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        areatxt.setForeground(new java.awt.Color(153, 153, 0));
        areatxt.setRows(5);
        jScrollPane1.setViewportView(areatxt);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OLT", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel2.setToolTipText("");
        jPanel2.setName(""); // NOI18N

        ComboBoxOlts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "CM-121", "CM-122", "PI-221", "JCP-521" }));
        ComboBoxOlts.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxOltsItemStateChanged(evt);
            }
        });
        ComboBoxOlts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxOltsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ComboBoxOlts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(ComboBoxOlts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnEnviar.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        panelDatos.setBackground(new java.awt.Color(0, 153, 153));
        panelDatos.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), null));
        panelDatos.setToolTipText("");
        panelDatos.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel1.setText("Puerto");

        txtPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel2.setText("Posicion");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel3.setText("Serial");

        txtSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel4.setText("Nom. y Apellido");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel5.setText("Telefono");

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel6.setText("User");

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel7.setText("Password");

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel8.setText("Puerto IPTV");

        grupoIPTV.add(radioiptvcero);
        radioiptvcero.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        radioiptvcero.setText("0");
        radioiptvcero.setBorder(null);
        radioiptvcero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioiptvceroActionPerformed(evt);
            }
        });

        grupoIPTV.add(radioiptvunoOdos);
        radioiptvunoOdos.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        radioiptvunoOdos.setText("1/2");
        radioiptvunoOdos.setBorder(null);

        grupoIPTV.add(radioiptv3);
        radioiptv3.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        radioiptv3.setText("3");
        radioiptv3.setBorder(null);

        grupoIPTV.add(radioiptvcuatro);
        radioiptvcuatro.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        radioiptvcuatro.setText("4");
        radioiptvcuatro.setBorder(null);

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(radioiptvcero)
                .addGap(18, 18, 18)
                .addComponent(radioiptvunoOdos)
                .addGap(18, 18, 18)
                .addComponent(radioiptv3)
                .addGap(18, 18, 18)
                .addComponent(radioiptvcuatro)
                .addGap(22, 22, 22))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPos, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTel)
                            .addComponent(txtUser)
                            .addComponent(txtNomyApe)
                            .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioiptvunoOdos)
                    .addComponent(radioiptv3)
                    .addComponent(radioiptvcuatro)
                    .addComponent(radioiptvcero))
                .addGap(19, 19, 19))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(11, 11, 11)
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(txtPos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(txtNomyApe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGap(18, 18, 18)
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGap(20, 20, 20)
                    .addComponent(jLabel8)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)), null));
        jPanel4.setToolTipText("");
        jPanel4.setName(""); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("ONU-CONFIG");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel10.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("V4.0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnEnviar)
                        .addGap(41, 41, 41)
                        .addComponent(btnLimpiar)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar)
                            .addComponent(btnEnviar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenuBar1.setBackground(javax.swing.UIManager.getDefaults().getColor("MenuBar.shadow"));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/terminal.png"))); // NOI18N
        jMenu1.setText("Shows");

        itemInterfaceOLT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/itemcmd01.png"))); // NOI18N
        itemInterfaceOLT.setText("Interface OLT");
        itemInterfaceOLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInterfaceOLTActionPerformed(evt);
            }
        });
        jMenu1.add(itemInterfaceOLT);

        itemInterfaceOnu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/itemcmd01.png"))); // NOI18N
        itemInterfaceOnu.setText("Interface ONU");
        itemInterfaceOnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInterfaceOnuActionPerformed(evt);
            }
        });
        jMenu1.add(itemInterfaceOnu);

        itemOnuRunning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/itemcmd01.png"))); // NOI18N
        itemOnuRunning.setText("ONU Running");
        itemOnuRunning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOnuRunningActionPerformed(evt);
            }
        });
        jMenu1.add(itemOnuRunning);

        itemPotencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/itemcmd01.png"))); // NOI18N
        itemPotencia.setText("Potencia");
        itemPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPotenciaActionPerformed(evt);
            }
        });
        jMenu1.add(itemPotencia);

        itemOnuUnconfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/itemcmd01.png"))); // NOI18N
        itemOnuUnconfig.setText("ONU Unconfig");
        itemOnuUnconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOnuUnconfigActionPerformed(evt);
            }
        });
        jMenu1.add(itemOnuUnconfig);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/numeral.png"))); // NOI18N
        jMenu2.setText("MAC");

        itemBuscarMac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/itemcmd01.png"))); // NOI18N
        itemBuscarMac.setText("Buscar Mac");
        itemBuscarMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarMacActionPerformed(evt);
            }
        });
        jMenu2.add(itemBuscarMac);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/itemcmd01.png"))); // NOI18N
        jMenuItem7.setText("MAC en PON");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/itemcmd01.png"))); // NOI18N
        jMenuItem8.setText("MAC en ONU");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        UpdatePassYPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        UpdatePassYPassword.setText("Cambiar User/Pass");
        UpdatePassYPassword.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                UpdatePassYPasswordMenuSelected(evt);
            }
        });
        jMenuBar1.add(UpdatePassYPassword);

        DeleteONU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        DeleteONU.setText("Eliminar ONU");
        DeleteONU.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                DeleteONUMenuSelected(evt);
            }
        });
        jMenuBar1.add(DeleteONU);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/puerto.png"))); // NOI18N
        jMenu5.setText("Puertos IPTV");
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu5MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu3.setText("Extras");

        mitmSearchOnu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/itemcmd01.png"))); // NOI18N
        mitmSearchOnu.setText("Buscar ONU");
        mitmSearchOnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmSearchOnuActionPerformed(evt);
            }
        });
        jMenu3.add(mitmSearchOnu);

        mitmRebootOnu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/itemcmd01.png"))); // NOI18N
        mitmRebootOnu.setText("Reboot ONU");
        mitmRebootOnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmRebootOnuActionPerformed(evt);
            }
        });
        jMenu3.add(mitmRebootOnu);

        mitmRestoreDOnu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/itemcmd01.png"))); // NOI18N
        mitmRestoreDOnu.setText("Restore Default ONU");
        mitmRestoreDOnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmRestoreDOnuActionPerformed(evt);
            }
        });
        jMenu3.add(mitmRestoreDOnu);

        mitmDistancia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/itemcmd01.png"))); // NOI18N
        mitmDistancia.setText("Distancia");
        mitmDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmDistanciaActionPerformed(evt);
            }
        });
        jMenu3.add(mitmDistancia);

        mitmStatePon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/itemcmd01.png"))); // NOI18N
        mitmStatePon.setText("Estado PON");
        mitmStatePon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmStatePonActionPerformed(evt);
            }
        });
        jMenu3.add(mitmStatePon);

        mitmInfoPon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/itemcmd01.png"))); // NOI18N
        mitmInfoPon.setText("Info PON");
        mitmInfoPon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmInfoPonActionPerformed(evt);
            }
        });
        jMenu3.add(mitmInfoPon);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

@Override public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo.png"));
        return retValue;
    }
    
 
    
    private void txtSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialActionPerformed

    private void itemInterfaceOLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInterfaceOLTActionPerformed
        olt.comando("show running-config interface gpon-olt_"+ txtPort.getText()+"\r\n", areatxt);
    }//GEN-LAST:event_itemInterfaceOLTActionPerformed

    private void radioiptvceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioiptvceroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioiptvceroActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if((txtPort.getText().equals("")) || (txtPos.getText().equals(""))  || (txtSerial.getText().equals(""))  || (txtNomyApe.getText().equals("")) || (txtTel.getText().equals("")) 
           || (txtUser.getText().equals("")) || (txtPass.getText().equals(""))){
            lanzarTiposDeMensaje("Los campos no pueden estar vacios");
        }
        else{
            olt.comando(//Asignacion de Gpon          
            "conf t \r\n"
            +"interface gpon-olt_"+txtPort.getText()+"\r\n"
            +" onu "+txtPos.getText()+" type ZXHN-F660 sn "+txtSerial.getText()+"\r\n"
            +"linktrap inform\r\n"
            +"!\r\n"
            //Configura Gpon con su puertos,vlan,etc.
            +"interface gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+"\r\n"
            +"sn-bind enable sn\r\n"
            +"tcont 1 name tcont1 profile INTERNET-BE\r\n"
            +"tcont 2 name tcont2 profile IPTV-F\r\n"
            +"gemport 1 unicast tcont 1 dir both queue 1\r\n"
            +"gemport 2 unicast tcont 2 dir both queue 1\r\n"
            +"switchport mode hybrid vport 1\r\n"
            +"switchport mode hybrid vport 2\r\n"
            +"service-port 1 vport 1 user-vlan "+this.vlanInternet+" user-etype PPPOE vlan "+this.vlanInternet+"\r\n"
            +"service-port 2 vport 2 user-vlan "+this.vlanIptv+" vlan "+this.vlanIptv+"\r\n"
            +"port-location format flexible-syntax vport 1\r\n"
            +"port-location sub-option remote-id enable vport 1\r\n"
            +"port-location sub-option remote-id name CM-GZ-121 vport 1\r\n"
            +"dhcp-option82 enable vport 2\r\n"
            +"pppoe-plus enable vport 1\r\n"
            +"name " +txtNomyApe.getText()+" tel "+txtTel.getText()+"\r\n"
            +"!\r\n"
            //Configuracion de IPTV
            +"pon-onu-mng gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+"\r\n"
            +"service ppp type internet iphost 1 gemport 1 cos 2 vlan "+this.vlanInternet+"\r\n"
            +"service iptv type iptv gemport 2 cos 5 vlan "+this.vlanIptv+"\r\n"
            +"pppoe 1 nat enable user "+txtUser.getText()+" password "+txtPass.getText()+"\r\n"
            +"vlan port wifi_0/1 mode tag vlan "+this.vlanInternet+" priority 2\r\n"
            +"security-mng 1 state enable ingress-type lan\r\n"
            +"security-mng 2 state enable mode permit\r\n"
            +"security-mng 2 start-src-ip 190.13.224.2 end 190.13.224.2\r\n"
            +" multicast vlan add vlanlist "+this.vlanIptv+"\r\n", areatxt);
            
            if(radioiptvunoOdos.isSelected()){
                olt.comando("vlan port eth_0/1 mode tag vlan "+this.vlanInternet+" priority 2\r\n"
                +"vlan port eth_0/2 mode tag vlan "+this.vlanInternet+" priority 2\r\n"
                +"vlan port eth_0/3 mode tag vlan "+this.vlanIptv+" priority 5\r\n"
                +"vlan port eth_0/4 mode tag vlan "+this.vlanIptv+" priority 5\r\n"
                +"multicast vlan tag-strip port eth_0/3 enable\r\n"
                +"multicast vlan tag-strip port eth_0/4 enable\r\n"
                +"dhcp-ip ethuni eth_0/3 from-internet\r\n"
                +"dhcp-ip ethuni eth_0/4 from-internet\r\n"
                +"!\r\n"
                +"igmp  mvlan "+this.vlanIptv+" receive-port gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+" vport 2\r\n", areatxt);
            }
            if(radioiptv3.isSelected()){
                olt.comando("vlan port eth_0/1 mode tag vlan "+this.vlanInternet+" priority 2\r\n"
                +"vlan port eth_0/2 mode tag vlan "+this.vlanIptv+" priority 5\r\n"
                +"vlan port eth_0/3 mode tag vlan "+this.vlanIptv+" priority 5\r\n"
                +"vlan port eth_0/4 mode tag vlan "+this.vlanIptv+" priority 5\r\n"
                +"multicast vlan tag-strip port eth_0/2 enable\r\n"
                +"multicast vlan tag-strip port eth_0/3 enable\r\n"
                +"multicast vlan tag-strip port eth_0/4 enable\r\n"
                +"dhcp-ip ethuni eth_0/2 from-internet\r\n"
                +"dhcp-ip ethuni eth_0/3 from-internet\r\n"
                +"dhcp-ip ethuni eth_0/4 from-internet\r\n"
                +"!\r\n"
                +"igmp  mvlan "+this.vlanIptv+" receive-port gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+" vport 2\r\n",areatxt);
            }
            if(radioiptvcuatro.isSelected()){
                olt.comando("vlan port eth_0/1 mode tag vlan "+this.vlanIptv+" priority 5\r\n"
                +"vlan port eth_0/2 mode tag vlan "+this.vlanIptv+" priority 5\r\n"
                +"vlan port eth_0/3 mode tag vlan "+this.vlanIptv+" priority 5\r\n"
                +"vlan port eth_0/4 mode tag vlan "+this.vlanIptv+" priority 5\r\n"
                +"multicast vlan tag-strip port eth_0/1 enable\r\n"
                +"multicast vlan tag-strip port eth_0/2 enable\r\n"
                +"multicast vlan tag-strip port eth_0/3 enable\r\n"
                +"multicast vlan tag-strip port eth_0/4 enable\r\n"
                +"dhcp-ip ethuni eth_0/1 from-internet\r\n"
                +"dhcp-ip ethuni eth_0/2 from-internet\r\n"
                +"dhcp-ip ethuni eth_0/3 from-internet\r\n"
                +"dhcp-ip ethuni eth_0/4 from-internet\r\n"
                +"!\r\n"
                +"igmp  mvlan "+this.vlanIptv+" receive-port gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+" vport 2\r\n", areatxt);
            }
            if(radioiptvcero.isSelected()){
                olt.comando("vlan port eth_0/1 mode tag vlan "+this.vlanInternet+" priority 2\r\n"
                +"vlan port eth_0/2 mode tag vlan "+this.vlanInternet+" priority 2\r\n"
                +"vlan port eth_0/3 mode tag vlan "+this.vlanInternet+" priority 2\r\n"
                +"vlan port eth_0/4 mode tag vlan "+this.vlanInternet+" priority 2\r\n"
                +"dhcp-ip ethuni eth_0/1 from-onu\r\n"
                +"dhcp-ip ethuni eth_0/2 from-onu\r\n"
                +"dhcp-ip ethuni eth_0/3 from-onu\r\n"
                +"dhcp-ip ethuni eth_0/4 from-onu\r\n"
                +"!\r\n", areatxt);
            }
           olt.comando("end\r\n", areatxt);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortActionPerformed

    private void ComboBoxOltsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxOltsItemStateChanged
        int seleccionado = ComboBoxOlts.getSelectedIndex(); 
        
        switch (seleccionado){
            case 1:
                 olt.conexion121("10.225.1.21",areatxt);
                 this.vlanInternet = "1121";
                 this.vlanIptv = "3121"; 
                 try{
                     if(olt.estadoOlt122()) olt.disconectOlt122();
                     if(olt.estadoOlt221()) olt.disconectOlt221();
                     if(olt.estadoOlt521()) olt.disconectOlt521();
                   
                 }catch(IOException ex){}
                 break;
                 
            case 2:
                  olt.conexion122("10.225.1.22",areatxt);
                  this.vlanInternet = "1122";
                  this.vlanIptv = "3122";
                  try{
              
                 if(olt.estadoOlt121()) olt.disconectOlt121();
                 if(olt.estadoOlt221()) olt.disconectOlt221();
                 if(olt.estadoOlt521()) olt.disconectOlt521();
                 }catch(IOException ex){}
                break;
            case 3:
                olt.conexion221("10.225.2.21",areatxt);
                this.vlanInternet = "1221";
                this.vlanIptv = "3221";
                try{
                if(olt.estadoOlt122()) olt.disconectOlt122();
                if(olt.estadoOlt121())  olt.disconectOlt121();
                if(olt.estadoOlt521())  olt.disconectOlt521();
                }catch(IOException ex){}
                break;
            case 4:
                olt.conexion521("10.225.5.21",areatxt);
                this.vlanInternet = "1521";
                this.vlanIptv = "3521";
                try{
                if(olt.estadoOlt121()) olt.disconectOlt121();
                if(olt.estadoOlt122())  olt.disconectOlt122();
                if(olt.estadoOlt221())  olt.disconectOlt221();
                }catch(IOException ex){}
                break;
        }
    }//GEN-LAST:event_ComboBoxOltsItemStateChanged

    private void ComboBoxOltsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxOltsActionPerformed
        
    }//GEN-LAST:event_ComboBoxOltsActionPerformed

    private void itemInterfaceOnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInterfaceOnuActionPerformed
         olt.comando("show running-config interface gpon-onu_"+this.txtPort.getText()+":"+this.txtPos.getText()+"\r\n"+
                    " \r\n", areatxt);
    }//GEN-LAST:event_itemInterfaceOnuActionPerformed

    private void itemOnuRunningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOnuRunningActionPerformed
        olt.comando("show onu running config gpon-onu_"+this.txtPort.getText()+":"+this.txtPos.getText()+"\r\n"+
                    " \r\n", areatxt);
    }//GEN-LAST:event_itemOnuRunningActionPerformed

    private void itemPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPotenciaActionPerformed
        olt.comando("show pon power attenuation gpon-onu_"+this.txtPort.getText()+":"+this.txtPos.getText()+"\r\n", areatxt);
    }//GEN-LAST:event_itemPotenciaActionPerformed

    private void itemOnuUnconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOnuUnconfigActionPerformed
        olt.comando("show gpon onu uncfg\r\n", areatxt);
    }//GEN-LAST:event_itemOnuUnconfigActionPerformed

    private void itemBuscarMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarMacActionPerformed
        olt.comando("show mac "+this.txtNomyApe.getText()+"\r\n", areatxt);
    }//GEN-LAST:event_itemBuscarMacActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        olt.comando("show mac gpon onu gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+"\r\n", areatxt);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        olt.comando("show mac gpon olt gpon-olt_"+txtPort.getText()+"\r\n", areatxt);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void mitmSearchOnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmSearchOnuActionPerformed
        olt.comando("show gpon onu by sn "+txtSerial.getText()+"\r\n", areatxt);
    }//GEN-LAST:event_mitmSearchOnuActionPerformed

    private void mitmRebootOnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmRebootOnuActionPerformed
        olt.comando("configure terminal\r\n"+
                    "pon-onu-mng gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+"\r\n"+
                    "reboot\r\n"+
                    "end\r\n", areatxt);
    }//GEN-LAST:event_mitmRebootOnuActionPerformed

    private void mitmRestoreDOnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmRestoreDOnuActionPerformed
        olt.comando("conf t\r\n"+
                    "pon-onu-mng gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+"\r\n"+
                    "restore factory\r\n"+
                    "end\r\n", areatxt);
    }//GEN-LAST:event_mitmRestoreDOnuActionPerformed

    private void mitmDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmDistanciaActionPerformed
        olt.comando("show gpon onu distance gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+"\r\n", areatxt);
    }//GEN-LAST:event_mitmDistanciaActionPerformed

    private void mitmStatePonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmStatePonActionPerformed
        olt.comando("show gpon onu state gpon-olt_"+txtPort.getText()+"\r\n", areatxt);
    }//GEN-LAST:event_mitmStatePonActionPerformed

    private void mitmInfoPonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmInfoPonActionPerformed
        olt.comando("show gpon onu baseinfo gpon-olt_"+txtPort.getText()+"\r\n", areatxt);
    }//GEN-LAST:event_mitmInfoPonActionPerformed

    private void jMenu5MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu5MenuSelected
        if (radioiptvcero.isSelected()) {
            olt.comando("conf t\r\n"+
                        "pon-onu-mng gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+"\r\n"+
                        "vlan port eth_0/1 mode tag vlan "+ this.vlanInternet +" priority 2\r\n"+
                        "vlan port eth_0/2 mode tag vlan "+ this.vlanInternet +" priority 2\r\n"+
                        "vlan port eth_0/3 mode tag vlan "+ this.vlanInternet +" priority 2\r\n"+
                        "vlan port eth_0/4 mode tag vlan "+ this.vlanInternet +" priority 2\r\n"+
                        "multicast vlan tag-strip port eth_0/1 disable\r\n"+
                        "multicast vlan tag-strip port eth_0/2 disable\r\n"+
                        "multicast vlan tag-strip port eth_0/3 disable\r\n"+
                        "multicast vlan tag-strip port eth_0/4 disable\r\n"+
                        "dhcp-ip ethuni eth_0/1 from-onu\r\n"+
                        "dhcp-ip ethuni eth_0/2 from-onu\r\n"+
                        "dhcp-ip ethuni eth_0/3 from-onu\r\n"+
                        "dhcp-ip ethuni eth_0/4 from-onu\r\n"+
                        "exit\r\n"+
                        "end\r\n", areatxt);
        }
        else if (radioiptvunoOdos.isSelected()) {
            olt.comando("conf t\r\n"+
                        "pon-onu-mng gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+"\r\n"+
                        "vlan port eth_0/1 mode tag vlan "+ this.vlanInternet +" priority 2\r\n"+
                        "vlan port eth_0/2 mode tag vlan "+ this.vlanInternet +" priority 2\r\n"+
                        "vlan port eth_0/3 mode tag vlan "+ this.vlanIptv +" priority 5\r\n"+
                        "vlan port eth_0/4 mode tag vlan "+ this.vlanIptv +" priority 5\r\n"+
                        "multicast vlan tag-strip port eth_0/1 disable\r\n"+
                        "multicast vlan tag-strip port eth_0/2 disable\r\n"+
                        "multicast vlan tag-strip port eth_0/3 enable\r\n"+
                        "multicast vlan tag-strip port eth_0/4 enable\r\n"+
                        "dhcp-ip ethuni eth_0/1 from-onu\r\n"+
                        "dhcp-ip ethuni eth_0/2 from-onu\r\n"+
                        "dhcp-ip ethuni eth_0/3 from-internet\r\n"+
                        "dhcp-ip ethuni eth_0/4 from-internet\r\n"+
                        "exit\r\n"+
                        "igmp  mvlan "+this.vlanIptv+" receive-port gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+" vport 2\r\n"+
                        "end\r\n", areatxt);
        }
        else if (radioiptv3.isSelected()) {
            olt.comando("conf t\r\n"+
                        "pon-onu-mng gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+"\r\n"+
                        "vlan port eth_0/1 mode tag vlan "+ this.vlanInternet +" priority 2\r\n"+
                        "vlan port eth_0/2 mode tag vlan "+ this.vlanIptv +" priority 5\r\n"+
                        "vlan port eth_0/3 mode tag vlan "+ this.vlanIptv +" priority 5\r\n"+
                        "vlan port eth_0/4 mode tag vlan "+ this.vlanIptv +" priority 5\r\n"+
                        "multicast vlan tag-strip port eth_0/1 disable\r\n"+
                        "multicast vlan tag-strip port eth_0/2 enable\r\n"+
                        "multicast vlan tag-strip port eth_0/3 enable\r\n"+
                        "multicast vlan tag-strip port eth_0/4 enable\r\n"+
                        "dhcp-ip ethuni eth_0/1 from-onu\r\n"+
                        "dhcp-ip ethuni eth_0/2 from-internet\r\n"+
                        "dhcp-ip ethuni eth_0/3 from-internet\r\n"+
                        "dhcp-ip ethuni eth_0/4 from-internet\r\n"+
                        "exit\r\n"+
                        "igmp  mvlan "+this.vlanIptv+" receive-port gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+" vport 2\r\n"+
                        "end\r\n", areatxt);
        }
        else {
            olt.comando("conf t\r\n"+
                        "pon-onu-mng gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+"\r\n"+
                        "vlan port eth_0/1 mode tag vlan "+ this.vlanIptv +" priority 5\r\n"+
                        "vlan port eth_0/2 mode tag vlan "+ this.vlanIptv +" priority 5\r\n"+
                        "vlan port eth_0/3 mode tag vlan "+ this.vlanIptv +" priority 5\r\n"+
                        "vlan port eth_0/4 mode tag vlan "+ this.vlanIptv +" priority 5\r\n"+
                        "multicast vlan tag-strip port eth_0/1 enable\r\n"+
                        "multicast vlan tag-strip port eth_0/2 enable\r\n"+
                        "multicast vlan tag-strip port eth_0/3 enable\r\n"+
                        "multicast vlan tag-strip port eth_0/4 enable\r\n"+
                        "dhcp-ip ethuni eth_0/1 from-internet\r\n"+
                        "dhcp-ip ethuni eth_0/2 from-internet\r\n"+
                        "dhcp-ip ethuni eth_0/3 from-internet\r\n"+
                        "dhcp-ip ethuni eth_0/4 from-internet\r\n"+
                        "exit\r\n"+
                        "igmp  mvlan "+this.vlanIptv+" receive-port gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+" vport 2\r\n"+
                        "end\r\n", areatxt);
        }
    }//GEN-LAST:event_jMenu5MenuSelected

    private void DeleteONUMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_DeleteONUMenuSelected
        olt.comando("conf t\r\n"+
                    "interface gpon-olt_"+txtPort.getText()+"\r\n"
                    +"no onu "+txtPos.getText()+"\r\n"+
                    "end\r\n"+
                    "Eliminado con Exito!\r\n", areatxt);
    }//GEN-LAST:event_DeleteONUMenuSelected

    private void UpdatePassYPasswordMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_UpdatePassYPasswordMenuSelected
        olt.comando("conf t\r\n"+
                    "pon-onu-mng gpon-onu_"+txtPort.getText()+":"+txtPos.getText()+"\r\n"+
                    "no pppoe 1\r\n"+
                    "pppoe 1 nat enable user "+txtUser.getText()+" password "+txtPass.getText()+"\r\n"+
                    "end\r\n", areatxt);
    }//GEN-LAST:event_UpdatePassYPasswordMenuSelected

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        MyIcon icon = new MyIcon();
        int resp = JOptionPane.showConfirmDialog(null, "¿Estas seguro de borrar?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (resp == 0) {
            txtPort.setText("");
            txtPos.setText("");
            txtSerial.setText("");
            txtNomyApe.setText("");
            txtTel.setText("");
            txtUser.setText("");
            txtPass.setText("");
            radioiptvcero.setSelected(true);
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisorTelnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisorTelnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisorTelnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisorTelnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisorTelnet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxOlts;
    private javax.swing.JMenu DeleteONU;
    private javax.swing.JMenu UpdatePassYPassword;
    private javax.swing.JTextArea areatxt;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.ButtonGroup grupoIPTV;
    private javax.swing.JMenuItem itemBuscarMac;
    private javax.swing.JMenuItem itemInterfaceOLT;
    private javax.swing.JMenuItem itemInterfaceOnu;
    private javax.swing.JMenuItem itemOnuRunning;
    private javax.swing.JMenuItem itemOnuUnconfig;
    private javax.swing.JMenuItem itemPotencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mitmDistancia;
    private javax.swing.JMenuItem mitmInfoPon;
    private javax.swing.JMenuItem mitmRebootOnu;
    private javax.swing.JMenuItem mitmRestoreDOnu;
    private javax.swing.JMenuItem mitmSearchOnu;
    private javax.swing.JMenuItem mitmStatePon;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JRadioButton radioiptv3;
    private javax.swing.JRadioButton radioiptvcero;
    private javax.swing.JRadioButton radioiptvcuatro;
    private javax.swing.JRadioButton radioiptvunoOdos;
    private javax.swing.JTextField txtNomyApe;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtPos;
    private javax.swing.JTextField txtSerial;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
